/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package auto_grader.screen_panels;

import java.awt.CardLayout;

import auto_grader.User_Interface;

/**
 *
 * @author selbst
 */
public class Start_Class_Panel extends javax.swing.JPanel {
	private User_Interface parent;
    /**
     * Creates new form Start_Class_Panel
     */
    public Start_Class_Panel(User_Interface parent) {
    	this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        header_panel = new javax.swing.JPanel();
        start_class_header = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        class_name_label = new javax.swing.JLabel();
        id_help = new javax.swing.JButton();
        add_assignment_button = new javax.swing.JButton();
        finish_button = new javax.swing.JButton();
        username_label2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 163, 210));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(696, 640));
        setPreferredSize(new java.awt.Dimension(696, 640));

        header_panel.setBackground(new java.awt.Color(102, 163, 210));
        header_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 86, 123), 3));
        header_panel.setMinimumSize(new java.awt.Dimension(466, 153));

        start_class_header.setFont(new java.awt.Font("Purisa", 1, 48)); // NOI18N
        start_class_header.setForeground(new java.awt.Color(255, 255, 255));
        start_class_header.setText("Start Class");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(start_class_header)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(start_class_header, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label2.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        label2.setText("Class ID:");

        name_field.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });

        id.setBackground(new java.awt.Color(255, 255, 255));
        id.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        id.setText("class-id");
        id.setOpaque(true);

        class_name_label.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        class_name_label.setText("Class Name:");

        id_help.setBackground(new java.awt.Color(102, 163, 210));
        id_help.setIcon(new javax.swing.ImageIcon("/home/selbst/Desktop/android/handwriting/HandwritingV008/images/question_mark_small.png")); // NOI18N

        add_assignment_button.setBackground(new java.awt.Color(37, 86, 123));
        add_assignment_button.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        add_assignment_button.setForeground(new java.awt.Color(255, 255, 255));
        add_assignment_button.setText("Add First Assignment");
        add_assignment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_assignment_buttonActionPerformed(evt);
            }
        });

        finish_button.setBackground(new java.awt.Color(37, 86, 123));
        finish_button.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        finish_button.setForeground(new java.awt.Color(255, 255, 255));
        finish_button.setText("Finish");
        finish_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_buttonActionPerformed(evt);
            }
        });

        username_label2.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        username_label2.setText("Or");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(class_name_label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(id_help, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(name_field))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finish_button, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_assignment_button, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(username_label2)
                        .addGap(321, 321, 321))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class_name_label))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2)
                    .addComponent(id_help, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(add_assignment_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finish_button)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void add_assignment_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        ((CardLayout)parent.getContentPane().getLayout()).show(parent.getContentPane(), "add_assignment");
    }

    private void finish_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JButton add_assignment_button;
    private javax.swing.JLabel class_name_label;
    private javax.swing.JButton finish_button;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel id;
    private javax.swing.JButton id_help;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel start_class_header;
    private javax.swing.JLabel username_label2;
    // End of variables declaration
}
