/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package auto_grader.screen_panels;

import java.awt.CardLayout;

import auto_grader.User_Interface;

/**
 *
 * @author selbst
 */
public class Title_Panel extends javax.swing.JPanel {
	private User_Interface parent;
	
    /**
     * Creates new form TItle_Panel
     */
    public Title_Panel(User_Interface parent) {
    	this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentbutton_img = new javax.swing.JButton();
        studentbutton_text = new javax.swing.JButton();
        teachbutton_img = new javax.swing.JButton();
        teachbutton_text = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 163, 210));

        jPanel6.setBackground(new java.awt.Color(102, 163, 210));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 86, 123), 3));
        jPanel6.setMinimumSize(new java.awt.Dimension(466, 153));

        jLabel7.setFont(new java.awt.Font("Purisa", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Handy");

        jLabel8.setFont(new java.awt.Font("Purisa", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Chem");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        studentbutton_img.setBackground(new java.awt.Color(63, 146, 210));
        studentbutton_img.setIcon(new javax.swing.ImageIcon("images/student_avatar.PNG")); // NOI18N
        studentbutton_img.setText("jButton2");

        studentbutton_text.setBackground(new java.awt.Color(63, 146, 210));
        studentbutton_text.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        studentbutton_text.setText("Student");
        studentbutton_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentbutton_textActionPerformed(evt);
            }
        });

        teachbutton_img.setBackground(new java.awt.Color(63, 146, 210));
        teachbutton_img.setIcon(new javax.swing.ImageIcon("images/teacher_avatar.PNG")); // NOI18N
        teachbutton_img.setText("jButton1");
        teachbutton_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachbutton_imgActionPerformed(evt);
            }
        });

        teachbutton_text.setBackground(new java.awt.Color(63, 146, 210));
        teachbutton_text.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        teachbutton_text.setText("Teacher");
        teachbutton_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachbutton_textActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentbutton_img, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentbutton_text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teachbutton_img, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teachbutton_text, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teachbutton_img, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teachbutton_text, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentbutton_text, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentbutton_img, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    
    private void studentbutton_imgActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        ((CardLayout)parent.getContentPane().getLayout()).show(parent.getContentPane(), "login");
    }              
    private void studentbutton_textActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        ((CardLayout)parent.getContentPane().getLayout()).show(parent.getContentPane(), "login");
    }                                                  

    private void teachbutton_imgActionPerformed(java.awt.event.ActionEvent evt) {                                                
        ((CardLayout)parent.getContentPane().getLayout()).show(parent.getContentPane(), "login");
    }                                               

    private void teachbutton_textActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        ((CardLayout)parent.getContentPane().getLayout()).show(parent.getContentPane(), "login");
    }                                                

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton studentbutton_img;
    private javax.swing.JButton studentbutton_text;
    private javax.swing.JButton teachbutton_img;
    private javax.swing.JButton teachbutton_text;
    // End of variables declaration                   
}
