package auto_grader.screen_panels;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Iterator;
import java.util.LinkedList;

import auto_grader.User_Interface;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author selbst
 */
public class Login_Panel extends javax.swing.JPanel {
	private User_Interface parent;
	private String[] user;
	
	private LinkedList<String> all_usernames;
	private LinkedList<String> all_passwords;

    /**
     * Creates new form Login_Screen
     */
    public Login_Panel(User_Interface parent) {
    	this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        login_button = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        register_button = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 163, 210));

        login_button.setBackground(new java.awt.Color(102, 163, 210));
        login_button.setFont(new java.awt.Font("Purisa", 1, 48)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("Login");
        login_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 62, 107), 3));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        username_label.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        username_label.setText("Username:");

        password_label.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        password_label.setText("Password:");

        username_field.setFont(new java.awt.Font("Purisa", 1, 18)); // NOI18N
        username_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_fieldActionPerformed(evt);
            }
        });

        password_field.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        password_field.setEchoChar('\u25cf');
        password_field.setMinimumSize(new java.awt.Dimension(10, 43));
        password_field.setPreferredSize(new java.awt.Dimension(10, 43));
        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });

        register_button.setBackground(new java.awt.Color(37, 86, 123));
        register_button.setFont(new java.awt.Font("Purisa", 1, 24)); // NOI18N
        register_button.setForeground(new java.awt.Color(255, 255, 255));
        register_button.setText("Register");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(password_label)
                                .addGap(24, 24, 24)
                                .addComponent(password_field, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(username_label)
                                .addGap(18, 18, 18)
                                .addComponent(username_field, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_label)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password_label)
                    .addComponent(password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(register_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {
    	if (all_usernames != null && username_field.getText() != null && password_field.getPassword() != null) {
    		System.out.println(all_usernames.getFirst());
    		Iterator<String> pass_iterator = all_passwords.iterator();
    		for (String s : all_usernames) {
    			String p = pass_iterator.next();
    			System.out.println(password_field.getPassword() + " =? " + p + "\n" + username_field.getText() + " =? " + s);
    			if (s != null && p != null) {
    			if (s.equals(username_field.getText())) {
    				if (p.equals(password_field.getText())) {
    					parent.set_username(s);
    					parent.load_classes();
    		        	((CardLayout)parent.getContentPane().getLayout()).show(parent.getContentPane(), "teacher_manager");
    				}
    			}
    			}
    		}
    	}
    }

    private void username_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    public void get_users() {
    	System.out.println("get_users");
    	all_usernames = new LinkedList<String>();
    	all_passwords = new LinkedList<String>();

		try {
			BufferedReader reader  = new BufferedReader(new FileReader("handwriter/auto_grader/user_interface/instructor/users/users.save"));
			String[] user = new String[2];
			while ((user[0] = reader.readLine()) != null) {
				user[1] = reader.readLine();
				System.out.println(user[0] + ", " + user[1]);
				all_usernames.add(user[0]);
				all_passwords.add(user[1]);
			}
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

    }
    // Variables declaration - do not modify
    private javax.swing.JButton login_button;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel password_label;
    private javax.swing.JButton register_button;
    private javax.swing.JTextField username_field;
    private javax.swing.JLabel username_label;
    // End of variables declaration
}
